label_list: ['CT', 'T']
enemy_list: ['CT']

# computer settings
conf: 0.35 # confidence interval
smooth: 0.8 # hypter parameter for moving smooth
resolution_x: 1920  # screen horizontal resolution

# lock hyperparameter
pos_factor: 0.2 # larger, closer to the head
max_lock_dis: 320 # auto lock if target distance smaller than this value, and press 'mouse_button' 
max_step_dis: 120 # max movement for each iteration (more smooth)
max_pid_dis: 20 # enanble pid control if target distance is smaller than this distance
max_shoot_dis: 50 # maximum distance to auto shoot
pidx_kp: 1.2
pidx_kd: 3.51
pidx_ki: 0.0
pidy_kp: 1.22
pidy_kd: 0.24   
pidy_ki: 0.0

# mouse settings
mouse_button_1: x2
mouse_button_2: x2 # pressing this button to start auto lock
auto_lock_button: x1 # turn on and off auto lock

# other functions
save_screenshot: False # auto save screenshot when press 'mouse_button' (collect false negative) or detected target (collect false positive)
visualization: False # show detection window, turn off to reduce cpu and gpu usage
speed_test: False # speed test before start
print_button: False # show current pressed button
delay: 0 # sleep for each iteration





